name: Feature Request
description: Suggest a new resource, pattern, or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
      placeholder: Describe your suggestion...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Architecture Pattern
        - New Resource/Link
        - Documentation Improvement
        - Example Code
        - Other
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why would this be valuable?
      placeholder: Explain the benefit...
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Any relevant links or references?
      placeholder: |
        - https://example.com/resource
        - Book: "Clean Architecture"
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute this myself
          required: false
